### ISSUE TITLE
r-buildpack issue concerning libv8-dev or libnode-dev

### ISSUE THREAD

**Issue by bparsons5** [cloudfoundry/r-buildpack#10]
Hello, I am running into an issue where my R shiny app cannot build on CF due to the r-buildpack not having libv8-dev or libnode-dev ubuntu packages. I also cannot unfortunately create my own custom buildpack due to our private PCF isntance. I would like to put in a request to update the r-buildpack to include libv8-dev if possible.

**Comment by dfreilich** [comment]
@bparsons5 Thanks for the feedback! If all that is necessary is the `libnode-dev` package, you should be able to use the [apt-buildpack](https://github.com/cloudfoundry/apt-buildpack/), together with r buildpack, using [multi-buildpack functionality](https://docs.cloudfoundry.org/buildpacks/use-multiple-buildpacks.html) to download `libnode-dev` and allow your app to run. 

Closing this for now. Feel free to reopen it if this doesn't work, and we'll look into prioritizing it.
