### ISSUE TITLE
Need libv8-dev and/or libnode-dev packages in the r-buildpack

### ISSUE THREAD

**Issue by bparsons5** [cloudfoundry/r-buildpack#11]
Hello, I have an issue where my R shiny app cannot build on CF due to the r-buildpack not having libv8-dev or libnode-dev ubuntu packages. The reason being that the security policy for my company does not allow us to choose other options to get around this. It would be awesome if you all could include these two packages in an updated r-buildpack.

**Comment by dfreilich** [comment]
Hey @bparsons5 , thanks for filing this! The `r-buildpack isn't our highest priority, so it may not get looked at right away, but we'll get to it.

**Comment by bparsons5** [comment]
Hello @dfreilich , I appreciate the response. Just keep me in the loop so my team and I can stay on top of this. Thank you.

**Comment by ryanmoran** [comment]
@bparsons5 have you tried using the [multi-buildpack support](https://docs.cloudfoundry.org/buildpacks/use-multiple-buildpacks.html) in Cloud Foundry? It might be possible to use the nodejs-buildpack and the r-buildpack together to do this.

**Comment by inflightfailure** [comment]
@ryanmoran I'm in the same situation as @bparsons5 and I tried multi-buildpack deployments with a variety of buildpack combinations and was unable to resolve the issue. Unfortunately our organizational security posture prevents the use of custom buildpacks, so we can't pursue that option either

**Comment by ryanmoran** [comment]
@inflightfailure can you use the [apt-buildpack](https://github.com/cloudfoundry/apt-buildpack)? 

The main issue is that buildpacks aren't really in the business of adding packages to the OS. We've created the apt-buildpack for these cases, but ideally libraries like libv8 and libnode should be included in the underlying stack root fs.

It's unlikely that we would make an exception to include this package as it impacts all users of the R buildpack and isn't functionality that aligns with the behavior of buildpacks or the specific functionality of supporting an R application.

**Comment by thitch97** [comment]
We are going to close this issue out for now. Please feel free to reopen this issue with a response to the above comment.
