### ISSUE TITLE
Creating a Binary CRAN Repository to Improve Useability

### ISSUE THREAD

**Issue by thomascjohnson** [cloudfoundry/r-buildpack#12]
If you've used this buildpack to create a Shiny app or any R application that depends on a lot of fancy R packages, you have probably run into the issue of not being able to successfully push due to the hard 15 minute time limit on builds. Installing devtools, ggplot2, dplyr and all of their dependencies takes a while and are not able to be installed in less than 15 minutes. These are extremely common packages to use in almost any R application, and most R users don't have the experience needed to simply add packages via the apt buildpack or some other method.

This was an issue for the EPA, and it was fixed by creating binary packages for cflinuxfs3: https://github.com/USEPA/cflinuxfs3-CRAN

This repository offers substantial utility for all R buildpack users, but it currently depends on me maintaining it. [I've created a package that handles adding packages to the repo](https://github.com/thomascjohnson/gitCRAN), but it still means that someone has to individually, manually add packages. 

I would like to open a discussion about how we could create either an automated system to build binary packages or setup a organizational structure to distribute the responsibility to more contributors. I think that this can be something fairly lean and simple, while also vastly improving the utility of the R buildpack for all users.

**Comment by dwillist** [comment]
@thomascjohnson This sounds like a great solution, We have existing pipelines that do something similar for other dependencies. Though I am hesitant to have a list of pre-compiled packages be the only solution for buildpack users. This solution would also be a long-term goal and require a lot of additional infrastructure on our end.

**Comment by kvedurmu** [comment]
Hey @thomascjohnson, we can look into doing this when the team implements the r-CNB.

**Comment by kvedurmu** [comment]
Closing this out. As mentioned before, we can look into supporting this in the R Paketo Buildpack

**Comment by NiPfi** [comment]
@kvedurmu Any news on said R Paketo Buildpack? I wasn't able to find a repository for it.
