### ISSUE TITLE
Problems with deploy in R 4.0

### ISSUE THREAD

**Issue by sebacea** [cloudfoundry/r-buildpack#15]
I want to deploy my app in ibmcloud but I got and error that seems to be related with [this](https://community.rstudio.com/t/shiny-app-publish-error-error-building-image/64211)

>What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`? 

`cf version 6.51.0+2acd15650.2020-04-07`

>What version of the buildpack you are using? 

1.1.4

>If you were attempting to accomplish a task, what was it you were attempting to do?

I run `ibmcloud cf push myapp`

>What did you expect to happen?

Succesful deployment

>What was the actual behavior?

```bash
  -----> R Buildpack version 1.1.4
   -----> Supplying R
   -----> Installing r 4.0.0
          Download [https://buildpacks.cloudfoundry.org/dependencies/r/r_4.0.0_linux_noarch_cflinuxfs3_4832644f.tgz]
   /tmp/contents132792537/deps/0/r/bin/exec/R: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
          **ERROR** Error installing packages: Error while installing packages: exit status 127
Error staging application: App staging failed in the buildpack compile phase
FAILED

```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by ryanmoran** [comment]
This should be fixed as of https://github.com/cloudfoundry/r-buildpack/releases/tag/v1.1.5.
