### ISSUE TITLE
Release: r-buildpack (Feb)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/r-buildpack#185]
Release reminder for r-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/r-buildpack/compare/v1.2.0..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/r-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by arjun024** [comment]
This release was done as a part of https://github.com/cloudfoundry/r-buildpack-release/issues/2
