### ISSUE TITLE
Precompiled CRAN for the R Buildpack

### ISSUE THREAD

**Issue by thomascjohnson** [cloudfoundry/r-buildpack#29]
I've created a precompiled CRAN that would very likely be of use to the users of the R buildpack: https://github.com/USEPA/cflinuxfs3-CRAN 

I've got it setup to automatically add packages when users from the USEPA Github org request them via a Github Issue. I just thought I'd share so that others can benefit from this.

**Comment by thomascjohnson** [comment]
And then later I found this out: http://dirk.eddelbuettel.com/blog/code/r4

Maybe using BSPM would be even better for the buildpack?

**Comment by kvedurmu** [comment]
This is really interesting, thanks for sharing! Eventually when we get to the v3 R Paketo Buildpack, we'll definitely consider how to make it easier for users to install R packages and avoid platform-level timeouts. 

I'm closing this out, as it's not really a request in the buildpack, but please share this out on the buildpacks slack channel so other users could benefit from it!
