### ISSUE TITLE
Buildpack auto-installs 'Suggests' dependencies

### ISSUE THREAD

**Issue by chrismasonthom-co** [cloudfoundry/r-buildpack#31]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

- cf.exe version 7.1.0+4c3168f9a.2020-09-09

What version of the buildpack you are using?

- 1.1.10

If you were attempting to accomplish a task, what was it you were attempting to do?

- deploy an R shiny application to a CF instance

What did you expect to happen?

- successfully install all R packages specified in r.yml

What was the actual behavior?

- fail to install some R packages which are **not** specified in r.yml

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

I am trying to deploy an application to a CF instance and am running into an issue when installing R packages, which I think is caused by this line:

https://github.com/cloudfoundry/r-buildpack/blob/319e668003ff4658de6a07ef68f0287f6773ce52/src/r/supply/supply.go#L120

In the line above, `dependencies=TRUE` is hard-coded - this means that all R packages listed in the 'Suggests' field of the description of a specified package are installed as well. This has two important consequences:

1. it really slows down a deployment, as the number of R packages being built from source is increased
2. it attempts to install packages for which system dependencies may not exist, causing failure

For example, the widely used `ggplot2` has `sf` listed in its 'Suggests' field, to enable certain examples of plotting spatial data. But `sf` won't install without valid installations of `libgdal`, `libgeos` and other system dependencies.

Would it be possible either to change this to `dependencies = NA` (the default in R), and if users need a package they can explicitly request it in the r.yml file, or to pass this in as an option from the r.yml? 

I appreciate this buildpack is not top priority, but I think this would be a very quick fix!

**Comment by ForestEckhardt** [comment]
This is an interesting idea. I will have to investigate whether or not doing this breaks any of our current functionality. Let me run a round of tests and get back to you!

**Comment by chrismasonthom-co** [comment]
That's great, thanks Forest. You'll have seen I've made a fork with this change in the interim - it's currently working for me, but definitely run some wider tests!

**Comment by elinork** [comment]
I've been struggling with staging timeouts, so I'd appreciate this, too, so we could start avoiding unnecessary dependencies.

**Comment by hedberg503** [comment]
I would also appreciate this, as I am also struggling with staging timeouts. Specifically with the sf package as a suggested dependency for ggplot2.

**Comment by menehune23** [comment]
Hi @chrismasonthom-co, thanks for the thorough post and suggestions. We're maintaining a lot of buildpacks these days, and our focus has also shifted quite a bit to the [Paketo buildpacks](github.com/paketo-buildpacks) that are more container-centric, so if you'd be willing to PR something based on your fork, we'd be happy to take a look. If there's a way to make this opt-in to lower risk of backwards incompatibilities, that would be optimal.

**Comment by ryanmoran** [comment]
For this implementation, I could imagine an API in the existing `r.yml` file that looks something like the following:

```yaml
---
cran_mirror: https://cran.r-project.org
dependencies:
- Depends
- Imports
packages:
- name: stringr
```

Where `dependencies` is expected to be an array with any of the allowed values: "Depends", "Imports", "LinkingTo", "Suggests", or "Enhances".

This would then create a `dependencies` option in the `install.packages` command like the following:

```R
install.packages(... dependencies=c("Depends", "Imports") ...)
```

If the field is missing or empty, then we can assume the `dependencies` option should take on its existing behavior which is to be set to `TRUE` like the following:

```R
install.packages(... dependencies=TRUE ...)
```

**Comment by menehune23** [comment]
Closing as stale. @chrismasonthom-co feel free to reopen if necessary
