### ISSUE TITLE
Any documentation for r.yml? 

### ISSUE THREAD

**Issue by avn4986** [cloudfoundry/r-buildpack#5]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.37.0+a40009753.2018-05-25

What version of the buildpack you are using?
R Buildpack version 0.0.5

If you were attempting to accomplish a task, what was it you were attempting to do?
Trying to deploy a sample shiny application with the following structure. 
    app.R – For me this is the bootstrapping application that has shiny related code
    init.R – This file is responsible for installing the dependencies.
    start.R - Main entry point in manifest.yml

What did you expect to happen?
Should be up and running without any problems because init.r takes care of installing dependencies. 

What was the actual behavior?
Staging failed because r.yml was not present. 

Output:
```
   2018-08-29T22:45:16.72+0530 [STG/0] OUT        **ERROR** Couldn't load r.yml: open /tmp/app/r.yml: no such file or directory
   2018-08-29T22:45:16.72+0530 [STG/0] ERR Failed to compile droplet: Failed to run all supply scripts: exit status 14
   2018-08-29T22:45:16.77+0530 [STG/0] OUT Exit status 223
   2018-08-29T22:45:16.77+0530 [STG/0] ERR Staging failed: STG: Exited with status 223
```

Please confirm where necessary:
* [ Y] I have included a log output
* [ Y] My log includes an error message
* [ N] I have included steps for reproduction

**Comment by avn4986** [comment]
@sclevine Could you point me to a multi package installation example? 
This doesn't seem to work 

```
---
packages:
    # Vendored Dependency URL
  - cran_mirror: https://cran.r-project.org
    packages:
      - name: 
            - shiny
            - stringr
```

**Comment by ameyer-pivotal** [comment]
@avn4986 We'll close this for now, but feel free to re-open if needed.
