### ISSUE TITLE
Libraries supported in R buildpack v1.0.5

### ISSUE THREAD

**Issue by dhruvbehl** [cloudfoundry/r-buildpack#6]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
2.65.0
6.32.0+0191c33d9.2017-09-26

What version of the buildpack you are using?
R buildpack v1.0.5

If you were attempting to accomplish a task, what was it you were attempting to do?
Attempting to understand if the following libraries are included as a part of R buildpack v1.0.5:

- libgsl0-dev (required for topicmodels)
- unixodbc-dev (required for r-oracle)
- libssh2-1-dev 
- libudunits2-dev 
- libmariadbclient-dev 
- libglu1-mesa-dev 
- libquantlib0-dev 
- libv8-3.14-dev 
- libprotobuf-dev 

What did you expect to happen?
Installation of packages such as topicmodels, R-MySQL etc.

What was the actual behavior?

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by Zanadar** [comment]
Cflinuxfs3 provides: https://github.com/cloudfoundry/cflinuxfs3/blob/master/receipt.cflinuxfs3.x86_64 which will give you an indication of what you have available. The apt buildpack could also be useful for install packages, but it does not work in all cases (notable libprotobuf).
