### ISSUE TITLE
IMPORTANT NOTICE: [r-buildpack] End of Support for R versions 4.0.x after 2021-07-03

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/r-buildpack#61]
The first release of the R buildpack after July 3, 2021 will no longer include R versions 4.0.x. These R versions will no longer be supported upstream.[1] Please migrate your R apps to supported versions of R before that time.

As always, the buildpacks team is happy to answer questions you may have about this deprecation in the #buildpacks Slack channel.

[1] - https://developer.r-project.org/

For more information on r dependencies and their deprecation dates, please refer to https://buildpacks.cloudfoundry.org/#/buildpacks

Thanks,
Buildpacks Team

**Comment by arjun024** [comment]
Removed from dependency-builds: https://github.com/cloudfoundry/buildpacks-ci/commit/2116aedf0fba76dea43bafe2973c5fa4aec5221a
Removed from buildpack: https://github.com/cloudfoundry/r-buildpack/commit/8458546922fd3f2836032ed0b23182a2952cc0d7

**Comment by arjun024** [comment]
Released in https://github.com/cloudfoundry/r-buildpack/releases/tag/v1.1.20
