### ISSUE TITLE
DT::DataTable and plotly outputs don't work on deployed apps. 

### ISSUE THREAD

**Issue by jlowe10** [cloudfoundry/r-buildpack#92]
I have managed to deploy a shiny app using your R buildpack. The only issue is that DT::DataTable and plotly objects don't work on the deployed app, even though they work locally. I think it's because they're not installing properly during the build.

For example, I get this message when I push:
`Warning message:
   In install.packages(c("plotly", "DT"), repos = "https://cran.r-project.org",  :
     installation of one or more packages failed,
     probably ‘units’, ‘s2’, ‘rgeos’, ‘sf’` 

A quick google suggests I need a dependency installed in order to install rgeos (https://stackoverflow.com/questions/53389181/installing-the-r-package-rgeos-on-linux-geos-config-not-found-or-not-executab). Is this something I am able to easily do while using the buildpack, or will I need to customise it myself?

Any help would be much appreciated!

James 

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "",
   "build": "",
   "support": "https://docs.cloud.service.gov.uk",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.london.cloud.service.gov.uk",
   "token_endpoint": "https://uaa.london.cloud.service.gov.uk",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.london.cloud.service.gov.uk:2222",
   "app_ssh_host_key_fingerprint": "2ZZlTNpKIRped1Fc1ZiSp1kBixoF0szohYfiR0qPLnU",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.london.cloud.service.gov.uk:443",
   "api_version": "2.166.0",
   "osbapi_version": "2.15",
   "user": "247944fc-c3a7-4edb-99ab-bdc19a587694"
}
cf version 7.2.0+be4a5ce2b.2020-12-10

What version of the buildpack you are using?
Latest

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploying a shiny app

What did you expect to happen?
The packages DT and plotly to install during the build phase and work for the deployed app. 

What was the actual behavior?
The objects don't appear in the deployed app. 

I think they failed to install because system dependencies were needed.  
installation of one or more packages failed,
     probably ‘units’, ‘s2’, ‘rgeos’, ‘sf’

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by menehune23** [comment]
Hi @jlowe10, thanks for posting. To help us debug further, could you please include a link to a minimal app repo that reproduces this issue, along with detailed reproduction steps?

**Comment by jlowe10** [comment]
Hi @menehune23, thanks for getting back to me. I would be happy to try, but I am swamped this week so I probably won't get back to you until next week at the earliest. 

In the meantime can I just check, are there examples of shiny apps deployed using your buildpack which include plotly/ DT::DataTable which work?

**Comment by menehune23** [comment]
@jlowe10 No problem -- happy to take a closer look once you get a chance to do that. Regarding examples, I'm not aware of any, and there don't seem to be any in the test fixtures.

**Comment by menehune23** [comment]
Closing as stale. @jlowe10 feel free to reopen if/when you get a chance to provide the repro app/details.
